#!/bin/bash
set -e

DIR=$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)
cd ~/otto/
Yellow='\033[0;33m'
NC='\033[0m'
Blue='\033[0;34m'
Purple='\033[0;35m'

# ---------------------------- Funktions ----------------------------------------
function update_version() {
  local fn="${1}"
  local replace="${2}"
  local version="${3}"


}

function check_package_versions() {
  for package in "${LOOKING_FOR[@]}"; do
    echo "#######################"
    printf "${Purple}${package}${NC} Version: \n"
    FILES_TO_UPDATE=$(rg -l "$package") || echo "nothing found in this root $DIR"
    for fn in $FILES_TO_UPDATE; do
      VERSION=$(sed -n "/val $package/p" $fn | sed -e 's/[^0-9]/ /g' -e 's/^ *//g' -e 's/ *$//g')
      printf "version $Yellow %s $NC in project $Blue%s$NC \n" "$VERSION" "$(dirname "${fn}")"
    done
  done

}

# ---------------------------- RUN ----------------------------------------

LOOKING_FOR=("keycloakResourceServerVersion" "reactiveSecurityVersion")



KEYCLOAK=202205021125070200
REACTIVE=202203140810310100

check_package_versions
echo "======================="
read -p "are this files okay to update? [y,N]: " okay
if [[ $okay == "y" || $okay == "Y" ]]; then
  for package in "${LOOKING_FOR[@]}"; do
    FILES_TO_UPDATE=$(rg -l "${package}") || echo "nothing found in this root $DIR"
    if [ "${package}" == "keycloakResourceServerVersion" ]; then
      replace="${KEYCLOAK}"
      elif [ "${package}" == "reactiveSecurityVersion" ]; then
      replace="${REACTIVE}"
    fi

    for fn in $FILES_TO_UPDATE; do
      VERSION=$(sed -n "/val $package/p" $fn | sed -e 's/[^0-9]/ /g' -e 's/^ *//g' -e 's/ *$//g')
      echo ${VERSION}
      printf "want to replace ${Yellow}${replace}${NC} with ${Purple}${VERSION}${NC} in project ${Blue}$(dirname ${fn})${NC} ???  [Y,n]: "
      read -p "" enter
      if [[ ${enter} == "n" || "${enter}" == "N" ]]; then
        printf "${Yellow}not updating${NC}\n"
      else
        sed -i "s/$VERSION/$replace/gi" "$fn"
        printf "${Purple}replaced VERSION ${VERSION} with $replace ${NC}\n"
      fi
    done
  done
  check_package_versions
  echo "############# done ##################"
fi
